name: Tests

on:
    pull_request:
        branches:
            - "**"
    push:
        branches:
            - "**"

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.10"]

        steps:
            - uses: actions/checkout@v3

            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Install
              run: |
                  pip install -e .

            - name:
                  Run tests with coverage
                  # public github actions runners seem to have 4 cpu cores
              run: |
                  pytest -N 4
